server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: quiz-service-route
          uri: http://localhost:8090
          predicates:
            - Path=/quiz-service/**
          filters:
            - StripPrefix=1
